CREATE TABLE question
(
questionId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
votes INT DEFAULT 0,
topic VARCHAR(100) NOT NULL,
content VARCHAR(10000) NOT NULL,
asker VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE answer
(
answerId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
questionId INT NOT NULL ,
votes INT DEFAULT 0,
content VARCHAR(1000) NOT NULL,
answerer VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (questionId)REFERENCES question(questionId)
);
