CREATE TABLE Questions( 
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,  
	name VARCHAR(30),
	email VARCHAR(50),
	topic VARCHAR(100),
	content VARCHAR(1024),
	date DATETIME,
	vote INT(6),
	answer INT(6)
);

CREATE TABLE Answer( 
	id INT(6) NOT NULL AUTO_INCREMENT,  
	qID INT(6),
	name VARCHAR(30),
	email VARCHAR(50),
	content VARCHAR(1024),
	date DATETIME,
	vote INT(6),
	CONSTRAINT PRiMARY KEY(id,qID),
	FOREIGN KEY qID REFERENCE Questions(id)
);